import axiosInstance from './apiClient';
import { GatewayRequest } from '@/types/plans';
import { v4 as uuidv4 } from 'uuid';

    const baseurl = import.meta.env.VITE_API_GATEWAY_URL;


// Define API functions
  export const fetchSuppliers = async () => {
  //  const response = await axiosInstance.get('/Supplier');

      let supplierUrl= `${baseurl}/Supplier`;
    const response = await axiosInstance.get(supplierUrl);
    console.log('Fetch suppliers:', response.data);

    return response.data;
  };

export const createSupplier = async (supplierObj: any) => {
  const payload = {
    ...supplierObj,
    id: 0, // Assuming id is auto-generated by the backend
  };

  const res = await fetch(`${baseurl}/Supplier`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
    redirect: "manual"
  });
  
  if (!res.ok) throw new Error('Failed to add supplier');
  return await res.json();
}

export const fetchPurchaseOrders = async () => {
  const purchaseOrderUrl = `${baseurl}/purchaseorder/save`;
  const response = await axiosInstance.get(purchaseOrderUrl);
  console.log('Fetch purchase orders:', response.data);
  return response.data;
};

